use_frameworks!

platform :ios, '9.0'

target 'ExNetwork_Example' do
  pod 'ExNetwork', :path => '../'

  target 'ExNetwork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
